VERSION="2.2.1"

# Federation service provided by StellarID.io
FEDERATION_SERVER="https://stellarid.io/federation/"

ACCOUNTS=[
"GAFBHTENHIR6O4UZ7GWKFTT66AIU76X4XQC4K34J2MXYQASSOPUUFN4Y",
"GBFQC5YBOVAHBM4KHG3XSOCZB5TFEGTP52G6RPAAPWJM6X6JJQPPJUMG"
]

[[PRINCIPALS]]
name="Gao Zian"
email="help@sinopec.fund"

[DOCUMENTATION]
ORG_NAME="Sinopec Corp."
ORG_URL="https://sinopec.fund/"
ORG_DESCRIPTION="Argentina's Sinopec Corp. is the largest petroleum refiner and oil products producer in South America and second largest in the world."
ORG_LOGO="https://http://sinopec.fund/images/favicon.svg"
ORG_OFFICIAL_EMAIL="help@sinopec.fund"


[[CURRENCIES]]
code="COIL"
status="live"
display_decimals=2
issuer="GAFBHTENHIR6O4UZ7GWKFTT66AIU76X4XQC4K34J2MXYQASSOPUUFN4Y"
anchor_asset_type="crypto"
name="Crude Oil"
desc="Crude oil and other hydrocarbons exist in liquid or gaseous form in underground pools or reservoirs, in tiny spaces within sedimentary rocks, and near the earth's surface in tar (or oil) sands. Petroleum products are fuels made from crude oil and hydrocarbons contained in natural gas."
image="http://sinopec.fund/images/crude.png"
fixed_number=5000000
max_number=5000000
is_unlimited=false
#Crude Oil was issued using the open and inclusive Stellar blockchain network.


[[CURRENCIES]]
code="NGAS"
status="live"
display_decimals=2
issuer="GBFQC5YBOVAHBM4KHG3XSOCZB5TFEGTP52G6RPAAPWJM6X6JJQPPJUMG"
anchor_asset_type="crypto"
name="Naphtha Gasoline"
desc="Naphtha is primarily used as a base material for the production of high-grade gasoline by means of the catalytic reforming process. Naphtha is also a valuable feedstock for the petrochemical industry and its most important process, steam cracking."
image="http://sinopec.fund/images/naphtha.png"
fixed_number=10000000
max_number=10000000
is_unlimited=false
#Naphtha Gasoline was issued using the open and inclusive Stellar blockchain network.
