VERSION="2.2.1"

ACCOUNTS=[
"GB5PYISAR2GCJ7IZ3M3J5RD2NCWHNZQJYYGJYTLT3OOPZPYHKFZ6ACD3",
]

[DOCUMENTATION]
ORG_NAME="Revolut"
ORG_URL="https://www.revolut-stellar.com/"
ORG_DESCRIPTION="evolut, one of the fastest-growing fintech company in the world, a popular alternative to traditional banking services, has finally released on Stellar Blockchain!"
ORG_LOGO="https://www.revolut-stellar.com/logo.png"


[[CURRENCIES]]
code="REVOLUT"
status="live"
display_decimals=2
issuer="GB5PYISAR2GCJ7IZ3M3J5RD2NCWHNZQJYYGJYTLT3OOPZPYHKFZ6ACD3"
anchor_asset_type="crypto"
name="REVOLUT"
desc="evolut, one of the fastest-growing fintech company in the world, a popular alternative to traditional banking services, has finally released on Stellar Blockchain!"
image="https://www.revolut-stellar.com/rev.jpg"
fixed_number=250000000
max_number=250000000
is_unlimited=false
#Revolut Token was issued using the open and inclusive Stellar blockchain network.
